### ISSUE TITLE
Was there supposed to be some code here?

### ISSUE THREAD

**Issue by sabracrolleton** [jingtaozf/s-dot#1]
I saw the request to add s-dot to quicklisp. Usually that happens only after there is actual working code. I don't see any here. Am I missing something?

**Comment by jingtaozf** [comment]
Yes, it is working, you can find demo codes in here:
https://github.com/jingtaozf/s-dot#examples

And the home page also contains the document for this library:
https://github.com/jingtaozf/s-dot#the-s-dot-language

**Comment by sabracrolleton** [comment]
Sorry. I missed the literate-lisp inclusion.
